spring:
  application:
    name: smbank
  profiles:
    active: oracle
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

app:
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521/XEPDB1
      username: SUPERMICRO_BANK
      password: SUPERMICRO_BANK
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
    tibero:
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      jdbc-url: jdbc:tibero:thin:@localhost:8629:tibero
      username: tibero
      password: tibero
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: oracle
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

---
spring:
  config:
    activate:
      on-profile: tibero
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
